name: 'Pipeline 1 - Terraform GKE'

on:
  push:
    branches:
      - main
    paths:
      - 'tp3/HIT3/terraform/gke/**'
  pull_request:
    paths:
      - 'tp3/HIT3/terraform/gke/**'

jobs:
  terraform:
    name: 'Terraform Plan & Apply GKE'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    defaults:
      run:
        working-directory: tp3/HIT3/terraform/gke

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/996435690701/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'terraform-bot@proyecto-sobel-grupo404.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
